db.url=jdbc:postgresql://ider-database.westeurope.cloudapp.azure.com:5433/h184905
db.user=h184905
db.pass=pass

spring.datasource.url=jdbc:postgresql://ider-database.westeurope.cloudapp.azure.com:5433/h184905
spring.datasource.username=h184905
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.initializationFailTimeout=0
spring.datasource.hikari.connectionTimeout=2000

logging.level.org.springframework.boot.context.config=DEBUG
server.port=8080
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
server.servlet.jsp.init-parameters.development=true

spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false
spring.thymeleaf.cache=false

spring.mvc.hiddenmethod.filter.enabled=true

spring.main.lazy-initialization=true